---
AllCops:
  Exclude:
    - 'Guardfile'
    - 'Rakefile'
    - 'Vagrantfile'
    - 'Policyfile.rb'
    - 'Berksfile'
    - 'Thorfile'
    - 'Gemfile'
    - 'metadata.rb'
    - 'test/**/*'
    - 'bin/**'
    - 'vendor/**/*'
AlignParameters:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Naming/FileName:
  Enabled: false
PerceivedComplexity:
  Enabled: false
SpaceBeforeFirstArg:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
